server:
  port: 8080

spring:
  ai:
    ollama:
      chat:
        model: qwen2.5:7b
        enabled: true
      base-url: http://localhost:11434
    mcp:
      client:
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://localhost:9090
        stdio:
          connections:
            server2:
              command: java
              args:
                - -Dspring.ai.mcp.server.stdio=true
                - -Dspring.main.web-application-type=none
                - -Dspring.main.banner-mode=off
                - -jar
                - /Users/baoxiaomin/IdeaProjects/mcp_project/spring-ai-mcp-demo/spring-ai-mcp-stdio-server/target/spring-ai-mcp-stdio-server.jar
